version: '3.9'

services:
  gates:
    image: a3/gate
    build: ./Gateway
    ports:
      - 3001:3001
    restart: on-failure
    networks: 
      mynet:
        ipv4_address: "172.16.238.9"
    cpu_count: 1
    mem_limit: 100m
    # depends_on:
    # - mail
    # - back

  back:
    image: a3/back
    build: ./BACK
    ports:
      - 3000:3000
    restart: on-failure
    networks: 
      mynet:
        ipv4_address: "172.16.238.10"
    cpu_count: 1
    mem_limit: 100m

  mail:
    image: a3/mail
    build: ./MAIL
    ports:
      - 3003:3003
    restart: on-failure
    networks:
      mynet:
        ipv4_address: "172.16.238.11"
    cpu_count: 1
    mem_limit: 100m

networks: 
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24